# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDwxFPZq7f_Q1sAovZvprsU7DWmyUyK4

Fibonacci series
"""

n = 10
a = 0
b = 1

for i in range(n):
    print(a, end=" ")
    next = a + b
    a = b
    b = next